version: '2.3'
services:

  backend:
    build: .
    command: ./manage.py runserver 0.0.0.0:8080

    ports:
      - '80:8080'

    volumes:
      - '.:/opt/my-web-app'

    enviroment:
      - 'DJANGO SETTINGS MODULE=dev.settings'

    depends_on:
      - database

    database:
      image: postgres
    
    memcached:
      image: memcached

    mail:
        image: djfarrelly/maildev
        ports:
          - "9000:80"